"""empty message

Revision ID: ec59a7ce851a
Revises: 
Create Date: 2017-12-06 19:07:39.617777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec59a7ce851a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_searches')
    op.add_column('users', sa.Column('password_hash', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    op.create_table('user_searches',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('airport_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['airport_id'], ['airportcode.id'], name='user_searches_airport_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_searches_user_id_fkey')
    )
    # ### end Alembic commands ###
